accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreateNewsView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    path('newses/<int:category>', views.CategoryView.as_view(), name='newses_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('news-detail/<int:pk>', views.DetailView.as_view(), name='news_detail'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),
    # コメント機能：コメントの作成
    path('news/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    # コメント機能：コメントの削除
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

newsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

news/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(verbose_name='カテゴリ', max_length=20)

    def __str__(self):
        return self.title

class NewsPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE,
    )

    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT,
    )

    title = models.CharField(verbose_name='タイトル', max_length=200)
    comment = models.TextField(verbose_name='コメント')
    image1 = models.ImageField(verbose_name='イメージ1', upload_to='newses')
    image2 = models.ImageField(verbose_name='イメージ2', upload_to='newses', blank=True, null=True)
    posted_at = models.DateTimeField(verbose_name='投稿日', auto_now_add=True)
    
    def __str__(self):
        return self.title

# コメント機能：ニュース投稿に対するコメントを保存するモデル
class Comment(models.Model):
    # どのニュース投稿に対するコメントか
    news_post = models.ForeignKey(NewsPost, verbose_name='ニュース投稿', on_delete=models.CASCADE, related_name='comments')
    # コメントしたユーザー
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    # コメントの内容
    content = models.TextField(verbose_name='コメント内容')
    # コメントした日時
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)

    def __str__(self):
        return self.content[:20]

    class Meta:
        # 新しいコメントが上に来るように並び替え
        ordering = ['-posted_at']

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

news/forms.py
from django.forms import ModelForm
from .models import NewsPost, Comment

class NewsPostForm(ModelForm):
    class Meta:
        model = NewsPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

# コメント機能：コメント投稿用のフォーム
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        # ユーザーが入力するのはコメント内容だけ
        fields = ['content']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
    template_name = 'signup_success.html'

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView
from django.urls import reverse_lazy
from .forms import NewsPostForm, CommentForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import NewsPost, Comment

class IndexView(ListView):
    template_name = "index.html"
    queryset = NewsPost.objects.all().order_by('-posted_at')
    paginate_by = 9


@method_decorator(login_required, name='dispatch')
class CreateNewsView(CreateView):
    form_class = NewsPostForm
    template_name = "post_news.html"
    success_url = reverse_lazy('news:post_done')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    template_name = "post_success.html"

class CategoryView(ListView):
    template_name = "index.html"
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs['category']
        categories = NewsPost.objects.filter(category=category_id).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name = "index.html"
    paginate_by = 9

    def get_queryset(self):
        user_id = self.kwargs['user']
        user_posts = NewsPost.objects.filter(user=user_id).order_by('-posted_at')
        return user_posts
    
class DetailView(DetailView):
    template_name = "detail.html"
    model = NewsPost

    def get_context_data(self, **kwargs):
        # 親クラスのメソッドを呼び出してコンテキストを取得
        context = super().get_context_data(**kwargs)
        # コメント投稿フォームを追加
        context['comment_form'] = CommentForm()
        # このニュースに紐づくコメント一覧を追加
        context['comments'] = self.object.comments.all()
        return context

@method_decorator(login_required, name='dispatch')
class CommentCreateView(CreateView):
    form_class = CommentForm
    model = Comment

    def form_valid(self, form):
        # フォームのデータを保存せずにインスタンスを取得
        comment = form.save(commit=False)
        # URLパラメータからニュース投稿IDを設定
        comment.news_post_id = self.kwargs['pk']
        # コメントにログインユーザーを設定
        comment.user = self.request.user
        # データベースに保存
        comment.save()
        # ニュース詳細ページにリダイレクト
        return redirect('news:news_detail', pk=self.kwargs['pk'])

class MypageView(ListView):
    template_name = "mypage.html"
    paginate_by = 9

    def get_queryset(self):
        queryset = NewsPost.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset
    
class NewsDeleteView(DeleteView):
    model = NewsPost
    template_name = "news_delete.html"
    success_url = reverse_lazy('news:mypage')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class CommentDeleteView(DeleteView):
    model = Comment

    def get_success_url(self):
        # 削除後に戻るニュース詳細ページのURLを生成
        return reverse_lazy('news:news_detail', kwargs={'pk': self.object.news_post.pk})
    
    def delete(self, request, *args, **kwargs):
        # 削除対象のコメントを取得
        comment = self.get_object()
        # コメントの投稿者とログインユーザーが一致するか確認
        if comment.user == request.user:
            # 一致する場合は削除を実行
            return super().delete(request, *args, **kwargs)
        # 一致しない場合はニュース詳細ページにリダイレクト
        return redirect('news:news_detail', pk=comment.news_post.pk)

accounts/templates/logout.html
{% extends "base.html" %}
{% block title %}Log Out{% endblock %}
{% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>ログアウトしました</h3>
                <p><a href="{% url 'news:index' %}">トップページへ戻る</a></p>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/password_reset.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}
{% block contents %}
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードリセット</h3>
                <p>パスワードをリセットするには、登録したメールアドレスを入力してください。</p>
                <br>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="メールを受け取る"/><br>
                </form>
                <br>
                <p><a href="{% url 'news:index' %}">News</a></p>
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="">
  <head>
    <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>
<body>
    <div class="pad">
    </h2>パスワードのリセットが完了しました。</h2>
    <p>Your password has been set. You may go ahead and login</p>
    <br>
    <a href="{% url 'accounts:index' %}">Newsのトップページへ</a>
    </div>
</body>
</html>

accounts/templates/password_reset_sent.html
{% extends "base.html" %}
{% block title %}Send password reset {% endblock %}
{% block contents %}
<hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2 py-4">
                <h5>パスワードリセットメール送信完了</h5>
                <br>
                <h6>メールが届かない場合は、登録したメールアドレスであるかを確認し、迷惑メールフォルダをご確認ください。</h6>
                <br>
                <p><a href="{% url 'news:index' %}">News</a></p>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/signup_success.html
{% extends "base.html" %}
{% block title %}Registration Complete{% endblock %}
{% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>登録完了</h3>
                <p><a href="{% url 'accounts:login' %}">ログインページへ</a></p>
            </div>
        </div> 
    </div>
{% endblock %}

news/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" href="{% static 'assets/gogo.png' %}">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">ニュースを見よう！</h4>
          <p class="text-muted">誰でも参加できるニュース投稿サイトです。
          みんなで最新のニュースを共有しましょう！
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
            <li><a href="{% url 'news:mypage' %}" class="text-white">マイページ</a></li>
            <li><form method="post" action="{% url 'accounts:logout' %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-link text-white p-0">ログアウト</button>
            </form></li>
            <li><a href="{% url 'password_reset' %}" class="text-white">パスワードリセット</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email</a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
            <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'news:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>News</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  {% block contents %}
  {% endblock %}
</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="{% url 'news:index' %}">Back to top</a>
    </p>
    <p class="mb-1">News is &copy; Bootstrap, but please post a lot!</p>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

news/templates/detail.html
{% extends "base.html" %}
{% block title %}News Detail{% endblock %}
{% block contents %}
  <br>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h2>{{ object.title }}</h2>
        <p>{{ object.comment }}</p>
        <br>
        <p>{{ object.posted_at }}に投稿</p>
        <p><img src="{{ object.image1.url }}" class="img-fluid"></p>
        {% if object.image2 %}
        <p><img src="{{ object.image2.url }}" class="img-fluid"></p>
        {% endif %}
        {% if request.user == object.user %}
        <form method="POST" action="{% url 'news:news_delete' object.pk %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger my-2" onclick="return confirm('この投稿を削除しますか?');">削除</button>
        </form>
        {% endif %}

        <!-- コメント機能：ここから -->
        <hr>
        <h4>コメント ({{ comments.count }})</h4>
        
        <!-- ログインしている場合のみコメント投稿フォームを表示 -->
        {% if user.is_authenticated %}
        <div class="card mb-4">
          <div class="card-body">
            <h5>コメントを投稿</h5>
            <form method="POST" action="{% url 'news:comment_create' object.pk %}">
              {% csrf_token %}
              <div class="mb-3">
                {{ comment_form.content }}
              </div>
              <button type="submit" class="btn btn-primary">投稿</button>
            </form>
          </div>
        </div>
        {% else %}
        <!-- ログインしていない場合はログインリンクを表示 -->
        <p><a href="{% url 'accounts:login' %}">ログイン</a>してコメントを投稿</p>
        {% endif %}

        <!-- コメント一覧を表示 -->
        <div class="mt-4">
          {% for comment in comments %}
          <div class="card mb-3">
            <div class="card-body">
              <!-- コメントの投稿者と投稿日時 -->
              <h6 class="card-subtitle mb-2 text-muted">
                {{ comment.user.username }} - {{ comment.posted_at|date:"Y年m月d日 H:i" }}
              </h6>
              <!-- コメントの内容 -->
              <p class="card-text">{{ comment.content }}</p>
              <!-- 自分のコメントの場合のみ削除ボタンを表示 -->
              {% if request.user == comment.user %}
              <form method="POST" action="{% url 'news:comment_delete' comment.pk %}" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('このコメントを削除しますか?');">削除</button>
              </form>
              {% endif %}
            </div>
          </div>
          {% empty %}
          <!-- コメントが1件もない場合 -->
          <p>まだコメントがありません。</p>
          {% endfor %}
        </div>
        <!-- コメント機能：ここまで -->
      </div>
    </div>
  </div>
{% endblock %}

news/templates/index.html
{% extends "base.html" %}
{% block title %}News{% endblock %}

{% block contents %}
    {% include "news_title.html" %}

    {% include "news_list.html" %}

    {% include "pagination.html" %}

    {% endblock %}

news/templates/news_list.html
<div class="album py-5 bg-body-tertiary">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">
          <img src="{{ record.image1.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>
          <div class="card-body">
            <p class="card-text">
              {{ record.title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'news:news_detail' record.pk %}'">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'news:newses_cat' category=record.category.id %}'">{{ record.category.title }}</button>
              </div>
              <a href="{% url 'news:user_list' user=record.user.id %}">
              <small class="text-muted">{{ record.user.username }}</small>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

news/templates/news_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">News</h1>
        <p class="lead text-muted">ニュースを見てください</p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'news:post' %}" class="btn btn-primary my-2">投稿</a>
          <form method="post" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <button type="submit">ログアウト</button>
          </form>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>